### ISSUE TITLE
 'read' was not declared in this scope

### ISSUE THREAD

**Issue by avilleret** [Rekall/Rekall#3]
Trying to build on Ubuntu 15.10 using QtCreator, I got this error : 

~~~~
/home/antoine/lib-src/Rekall/watcher/folderwatcher_linux.cpp:133: erreur : 'read' was not declared in this scope
          len = read(fd, buffer.data(), buffer.size());
                                                     ^
~~~~~

**Comment by avilleret** [comment]
adding `#include <unistd.h>` on top of `folderwatcher_linux.cpp` fix this issue
